### ISSUE TITLE
Behavior fault on glpi 10.0.2

### ISSUE THREAD

**Issue by bern2b** [yllen/behaviors#46]
Hello,

it seems that the plugin does not work correctly for two parameters since the update to version 10.0.2 of glpi :
- Requester is mandatory: if this behavior is activated, the manual creation of a ticket by a technician is impossible. even after placing the requester, the plugin blocks the creation of the ticket indicating "requester required"

- Take the requester's group: this behavior works well with tickets by the mail collector or for tickets created from self-service. on the other hand, when a manual ticket is created by a technician, it does not assign the corresponding requester's group.

Have these issues been escalated? is a patch available?

Thanks in advance,

**Comment by bern2b** [comment]
Thanks for the feedback @yllen.
I'm sorry, I didn't understand how to fix the glpi bug. Could you tell me how to fix it?

**Comment by yllen** [comment]
Done in the plugin

**Comment by bern2b** [comment]
Sorry but, after correcting the file /plugins/behaviors/inc/ticket.class.php (removing lines 363-371) the problem persists.

when creating a ticket (with option "mandatory requester" and "take the requester's group" active) there is an error "mandatory requester".

**Comment by yllen** [comment]
Tested with glpi 10.0.3.
Have you some error in php-error.log?

**Comment by yllen** [comment]
Can you apply my last correction and tell me if OK for you?

**Comment by bern2b** [comment]
Sorry but even with this modification, the problem persists. 
I also tested on a test machine with a new Glpi 10.0.3 installation and the modifications did not correct the problem. 

The problem probably comes from the fact that the number of actors counter does not update (it remains at 0) until the ticket is created.

**Comment by yllen** [comment]
You have this issue only with a profile technician?
Can you test a ticket's creation with super-admin profile?
Have you some errors in file/_logs/php-error.log? insql_error.log?

**Comment by bern2b** [comment]
he problem arises in tech or super-admin profile
no trace in the php-error.log or sql_error.log

the number of actors does not increase when entering the ticket (see image) is this normal?
![Capture](https://user-images.githubusercontent.com/32790445/191904954-ac0a1aa0-efb2-4b26-acd7-27ff4a341326.JPG)

**Comment by yllen** [comment]
Le groupe du technicien sera ajouté APRES la validation du ticket, car avant je ne peux pas savoir que vous avez ajouté un technicien (je ne peux intervenir que sur l'objet en global et non une partie de l'objet, comme les acteurs d'un ticket)
Concernant le numéro de ticket, c'est GLPI qui gère cela dans l'affichage du ticket, je ne peux rien y faire

**Comment by rpalmeiro** [comment]
Same scenario. GLPI 10.0.3 and Behaviors 2.7.1

**Comment by yllen** [comment]
Can you tell me if this issue is still present in new version 2.7.2 newly published?

**Comment by eramos13** [comment]
Hi, I have version 2.7.2 of the plugin installed, but I have not added the requester group. I have GLPI 10.0.3 installed, and this is the behavior setting.

![group_requester](https://user-images.githubusercontent.com/73493165/197829007-593b5f2b-c7d0-4653-a019-7ea0e589acf8.jpg)

![setting_behavior](https://user-images.githubusercontent.com/73493165/197829028-8a0e4ce8-4c23-4986-b02f-7e770c6666f5.jpg)

**Comment by yllen** [comment]
The group is added after the ticket is created.
Have you test my latest release or have you test with the master branch before the release?

I made a test and not problem for me, the first group is added.
Does your user Usario01 have a group assign?

**Comment by eramos13** [comment]
> The group is added after the ticket is created. Have you test my latest release or have you test with the master branch before the release?
> 
> I made a test and not problem for me, the first group is added. Does your user Usario01 have a group assign?

After creating the ticket, the group was not added. I have tested with the master version and the latest release.

If the user User01 has a group added.

This only happens to me with a clean version of glpi 10.0.3. With a version that has information the error does not occur unless you remove a subentity.

I'm doing a clean configuration of the GLPI, because the one used in the company has many misconfigurations and I prefer to work with a clean version.

The same error occurs with a clean version of glpi 10.0.3 or earlier.

**Comment by yllen** [comment]
> This only happens to me with a clean version of glpi 10.0.3. With a version that has information the error does not occur unless you remove a subentity.

Is the group affected to the requester defined in the sub-entity you deleted?
In the clean version of GLPI, have you group affected to the requester in the same entity? 
Has the requester right to see group item?

If it's OK with an old version updated to 10.0.3, i think some information are missing in your clean version.

**Comment by yllen** [comment]
No news? i close
